### ISSUE TITLE
Utils in train_ms.py

### ISSUE THREAD

**Issue by mayqinxu** [liuhuang31/Megatts2_HierSpeechpp#1]
Hi liuhuang31, thanks for the project / repo! But I encountered an error while running inference_plm.py. The issue is related to the import statement in the train_ms.py file which reads:
`from Utils.ASR.models import ASRCNN`
It appears that Utils is neither a package nor a sub dir within the project. This results in an ImportError when attempting to execute inference_plm.py. I'm wondering how I should modify the code or add some dependencies to run the inference code?

**Comment by liuhuang31** [comment]
@mayqinxu hi, just comment the code of import ASRCNN, the ASRCNN is like mfa for align(but not use). If have other questions call me.

**Comment by mayqinxu** [comment]
> @mayqinxu hi, just comment the code of import ASRCNN, the ASRCNN is like mfa for align(but not use). If have other questions call me.

THX! I sucessfully ran the inference code!
